import {Song} from 'src/app/interfaces/song';

export const SONGS : Song[] =[

    {
      title: 'nombre 1',
      author: 'autor 1',
      year: 2022,
      album: 'album 1',
      genre: 'rock',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 2',
      author: 'autor 2',
      year: 2022,
      album: 'album 2',
      genre: 'pop',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 3',
      author: 'autor 3',
      year: 2022,
      album: 'album 3',
      genre: 'metal',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 4',
      author: 'autor 4',
      year: 2022,
      album: 'album 4',
      genre: 'country',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 5',
      author: 'autor 5',
      year: 2022,
      album: 'album 5',
      genre: 'death metal',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 6',
      author: 'autor 6',
      year: 2022,
      album: 'album 6',
      genre: 'metal',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 7',
      author: 'autor 7',
      year: 2022,
      album: 'album 7',
      genre: 'rock',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 8',
      author: 'autor 8',
      year: 2022,
      album: 'album 8',
      genre: 'pop',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 9',
      author: 'autor 9',
      year: 2022,
      album: 'album 9',
      genre: 'indie',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 10',
      author: 'autor 10',
      year: 2022,
      album: 'album 10',
      genre: 'soft rock',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 11',
      author: 'autor 11',
      year: 2022,
      album: 'album 11',
      genre: 'soft rock',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 12',
      author: 'autor 12',
      year: 2022,
      album: 'album 12',
      genre: 'blues',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 13',
      author: 'autor 13',
      year: 2022,
      album: 'album 13',
      genre: 'blues',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 14',
      author: 'autor 14',
      year: 2022,
      album: 'album 14',
      genre: 'rock',
      country: '',
      track: 0,
    },
    {
      title: 'nombre 15',
      author: 'autor 15',
      year: 2022,
      album: 'album 15',
      genre: 'electronic',
      country: '',
      track: 0,
    },

]
