import {Song} from 'src/app/interfaces/song';

export const SONGS : Song[] =[

    {
      title: 'Fight Back',
      author: 'Neffex',
      duration: '03:16',
      year: 2022,
      album: 'Fight Back',
      genre: 'Rap',
      country: 'USA',
      track: 1,
      rating: 2,
      url: 'src\assets\songs\Fight Back.mp3',
      cover_img: 'src\assets\images\covers\neffex.png',
    },
    {
      title: 'Showreel',
      author: 'Qube Sounds',
      duration: '02:14',
      year: 2022,
      album: 'Showreel',
      genre: 'Dance/Electronic',
      country: 'Ucrania',
      track: 2,
      rating: 2,
      url: 'src\assets\songs\Showreel.mp3',
      cover_img: 'src\assets\images\covers\QubeSounds.jpg',
    },
    {
      title: 'Price of Freedom',
      author: 'Zakhar Valaha',
      duration: '05:07',
      year: 2022,
      album: 'Price of Freedom',
      genre: 'New Age',
      country: 'India',
      track: 3,
      rating: 2,
      url: 'src\assets\songs\Price of Freedom.mp3',
      cover_img: 'src\assets\images\covers\ZakharValaha.jpg',
    },
    {
      title: 'Slow Trap',
      author: 'Anton Vlasov',
      duration: '02:34',
      year: 2020,
      album: 'Slow Trap',
      genre: 'Rap Hip Hop',
      country: 'Rusia',
      track: 4,
      rating: 2,
      url: 'src\assets\songs\Slow Trap.mp3',
      cover_img: 'src\assets\images\covers\Anton Vlasov.jpg',
    },
    {
      title: 'The Cradle of Your Soul',
      author: 'lemonmusicstudio',
      duration: '02:57',
      year: 2022,
      album: 'The Cradle of Your Soul',
      genre: 'Folk',
      country: 'Italia',
      track: 5,
      rating: 2,
      url: 'src\assets\songs\The Cradle of Your Soul.mp3',
      cover_img: 'src\assets\images\covers\lemonmusicstudio.jpg',
    },
    {
      title: 'Spirit Blossom',
      author: 'Roman Belov',
      duration: '01:48',
      year: 2022,
      album: 'Spirit Blossom',
      genre: 'Relax Lo-Fi',
      country: 'Rusia',
      track: 6,
      rating: 2,
      url: 'src\assets\songs\Spirit Blossom.mp3',
      cover_img: 'src\assets\images\covers\RomanBelov.jpg',
    },
    {
      title: 'Everything Feels New',
      author: 'Evgeny Bardyuzha',
      duration: '01:06',
      year: 2022,
      album: 'Evgeny Bardyuzha',
      genre: 'Dance/Electroni',
      country: 'Rusia',
      track: 7,
      rating: 2,
      url: 'src\assets\songs\Everything Feels New.mp3',
      cover_img: 'src\assets\images\covers\EvgenyBardyuzha.jpg',
    },
    {
      title: 'Moment',
      author: 'Serge Quadrado',
      duration: '03:32',
      year: 2022,
      album: 'SergeQuadrado',
      genre: 'Chill/Jazz',
      country: 'Spain',
      track: 8,
      rating: 2,
      url: 'src\assets\songs\Moment.mp3',
      cover_img: 'src\assets\images\covers\SergeQuadrado.jpg',
    },
    {
      title: 'Let It Go',
      author: 'ItsWatR',
      duration: '02:13',
      year: 2018,
      album: 'Let It Go',
      genre: 'Ambient',
      country: 'Rusia',
      track: 9,
      rating: 2,
      url: 'src\assets\songs\Let It Go.mp3',
      cover_img: 'src\assets\images\covers\ItsWatR.jpg',
    },
    {
      title: 'Just Relax',
      author: 'Lesfm',
      duration: '02:40',
      year: 2021,
      album: 'Just Relax',
      genre: 'Relax',
      country: 'Ucrania',
      track: 10,
      rating: 2,
      url: 'src\assets\songs\Just Relax.mp3',
      cover_img: 'src\assets\images\covers\Lesfm.jpg',
    },
    {
      title: 'Caves of Dawn',
      author: 'Guilherme Bernardes',
      duration: '03:22',
      year: 2021,
      album: 'Caves of Dawn',
      genre: 'Ambient',
      country: 'Brasil',
      track: 11,
      rating: 2,
      url: 'src\assets\songs\Caves of Dawn.mp3',
      cover_img: 'src\assets\images\covers\C:\Users\hecto\Desktop\GuilhermeBernardes.png',
    },
    {
      title: 'Town',
      author: 'Be Corbal',
      duration: '03:02',
      year: 2021,
      album: 'Town',
      genre: 'Electronic',
      country: 'Brasil',
      track: 12,
      rating: 2,
      url: 'src\assets\songs\Town.mp3',
      cover_img: 'src\assets\images\covers\BeCorbal.jpg',
    },
    {
      title: 'Battle Of The Dragons',
      author: 'Tommy Mutiu',
      duration: '03:57',
      year: 2022,
      album: 'Battle Of The Dragons',
      genre: 'Instrumental',
      country: 'Spain',
      track: 13,
      rating: 2,
      url: 'src\assets\songs\Battle Of The Dragons.mp3',
      cover_img: 'src\assets\images\covers\TommyMutiu.jpg',
    },
    {
      title: 'THE WAY HOME',
      author: 'Zakhar Valaha',
      duration: '03:46',
      year: 2021,
      album: 'THE WAY HOME',
      genre: 'Ambient',
      country: 'India',
      track: 14,
      rating: 2,
      url: 'src\assets\songs\THE WAY HOME.mp3',
      cover_img: 'src\assets\images\covers\ZakharValaha2.jpg',
    },
    {
      title: 'Jazzy Abstract Beat',
      author: 'Coma-Media',
      duration: '01:25',
      year: 2022,
      album: 'Aspiration',
      genre: 'Dance/Electronic',
      country: 'Ucrania',
      track: 15,
      rating: 2,
      url: 'src\assets\songs\Jazzy Abstract Beat.mp3',
      cover_img: 'src\assets\images\covers\Coma-Media.jpg',
    }

]
