import {Song} from 'src/app/interfaces/song';

export const SONGS : Song[] =[

    {
      title: 'Fight Back',
      author: 'Neffex',
      duration: 5,
      year: 2022,
      album: 'Fight Back',
      genre: 'Rap',
      country: 'USA',
      track: 1,
      cover_img: 'src\assets\images\neffex.png',
      localPath: 'src\assets\songs\Fight Back.mp3',
      rating: 2,
      url: '',
    },
    {
      title: 'nombre 2',
      author: 'autor 2',
      duration: 5,
      year: 2022,
      album: 'álbum 2',
      genre: 'pop',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 3',
      author: 'autor 3',
      duration: 5,
      year: 2022,
      album: 'álbum 3',
      genre: 'metal',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 4',
      author: 'autor 4',
      duration: 5,
      year: 2022,
      album: 'álbum 4',
      genre: 'country',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 5',
      author: 'autor 5',
      duration: 5,
      year: 2022,
      album: 'álbum 5',
      genre: 'death metal',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 6',
      author: 'autor 6',
      duration: 5,
      year: 2022,
      album: 'álbum 6',
      genre: 'metal',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 7',
      author: 'autor 7',
      duration: 5,
      year: 2022,
      album: 'álbum 7',
      genre: 'rock',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 8',
      author: 'autor 8',
      duration: 5,
      year: 2022,
      album: 'álbum 8',
      genre: 'pop',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 9',
      author: 'autor 9',
      duration: 5,
      year: 2022,
      album: 'álbum 9',
      genre: 'indie',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 10',
      author: 'autor 10',
      duration: 5,
      year: 2022,
      album: 'álbum 10',
      genre: 'soft rock',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 11',
      author: 'autor 11',
      duration: 5,
      year: 2022,
      album: 'álbum 11',
      genre: 'soft rock',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 12',
      author: 'autor 12',
      duration: 5,
      year: 2022,
      album: 'álbum 12',
      genre: 'blues',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 13',
      author: 'autor 13',
      duration: 5,
      year: 2022,
      album: 'álbum 13',
      genre: 'blues',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 14',
      author: 'autor 14',
      duration: 5,
      year: 2022,
      album: 'álbum 14',
      genre: 'rock',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    },
    {
      title: 'nombre 15',
      author: 'autor 15',
      duration: 5,
      year: 2022,
      album: 'álbum 15',
      genre: 'electronic',
      country: '',
      track: 0,
      rating: 2,
      url: '',
      cover_img: 'xxxx',
      localPath: 'xxxx',
    }

]
